#!/bin/bash
PHONE_MAC="<YOUR_PHONES_MAC_ADRESS>"   # You can get phone's mac adress from status section in android settings.
PHONE_KEY="~/.ssh/<YOUR_SECRET_KEY>"   # SSH secret key to use while connecting to phone.


script=$(realpath "$0")
scriptpath=$(dirname "$script")

if [ -e "$scriptpath"/phone_ip.log ] # Check if previous tmp file exists
    then phone_ip=$(cat "$scriptpath"/phone_ip.log)
elif [ "$1" != "scan" ]
    then echo "No ip log found, run 'teriyaki scan' first."; exit 1
fi

PHONE_SSH="ssh $phone_ip -p 8022 -i $PHONE_KEY"

case $1 in
    run)
        eval "$PHONE_SSH ${*:2}"
        ;;
    cp-set)
        eval "$PHONE_SSH termux-clipboard-set '$2'"
        ;;
    cp-get)
        $PHONE_SSH termux-clipboard-get
        ;;
    pull)
        scp -P 8022 -i "$PHONE_KEY" "$phone_ip":"$2" "$3"
        ;;
    push)
        scp -P 8022 -i "$PHONE_KEY" "$2" "$phone_ip":"$3"
        ;;
    share)
        eval "$PHONE_SSH rm -rf ./tmp/*"
        scp -P 8022 -i "$PHONE_KEY" "$2" "$phone_ip":./tmp/
        eval "$PHONE_SSH termux-share -a send ./tmp/*"
        ;;
    mount)
        sshfs -p 8022 -o IdentityFile="$PHONE_KEY" "$phone_ip":"$2" "$3"
        ;;
    scan)
        sudo test; printf "Updating the IP adress...\r"
        PHONE_IP=$(sudo arp-scan -l | grep $PHONE_MAC | awk '{print $1}')
        if [ -v $PHONE_IP ]; then
            echo "Couldn't find device's ip adress. Make sure it's connected to network and try again while phone screen is on."
            exit 127
        fi
        echo $PHONE_IP>$SCRIPTPATH/phone_ip.log
        printf "Updated! Current phone ip is: $PHONE_IP \n"
        ;;
    sms)
        $PHONE_SSH termux-sms-list -l 1 | jq -r '.[0]["body"]'
        ;;
    *)
        echo "Mini Termux Controller - github/Kebablord

scan                *  scan network to update phone's current IP adress
run <param>         -  run ssh commands or connect ssh terminal if no arg passed
cp-set <string>     -  copy the string to phone clipboard
cp-get              -  return the string from phone clipboard
sms                 -  display latest sms, useful for verification codes (root)
pull  <src> <dest>  -  pull the file from phone to computer
push  <src> <dest>  -  push the file to phone from computer
share <src>         -  share the media from computer to phone apps like whatsapp, telegram
mount <src> <dest>  -  use SSHFS to mount specific phone folder to linux folder
"
    ;;
esac

