#!/bin/bash
PHONE_MAC="<YOUR_PHONES_MAC_ADRESS>"   # You can get phone's mac adress from status section in android settings.
PHONE_KEY="~/.ssh/<YOUR_SECRET_KEY>"   # SSH secret key to use while connecting to phone.


script=$(realpath "$0")
scriptpath=$(dirname "$script")

MACtoIP() { # GETS THE CURRENT IP ADRESS OF PHONE FROM IT'S MAC ADRESS
    printf "Updating the IP adress...\r"
    phone_ip=$(sudo arp-scan -l | grep $PHONE_MAC | awk '{print $1}')
    if [ -z "$phone_ip" ]; then
        echo "Couldn't find device's ip adress. Make sure it's connected to network and try again while phone screen is on."
        exit 127
    fi
    echo "$phone_ip">"$scriptpath"/phone_ip.log
    echo -en "[\e[2K"; printf "Updated! Current phone ip is: %s \n" "$phone_ip"
}

if [ -e "$scriptpath"/phone_ip.log ] # Check if previous tmp file exists
    then phone_ip=$(cat "$scriptpath"/phone_ip.log)
elif [ "$1" != "scan" ]
    then echo "No ip log found, run 'sudo ./teriyaki scan' first."; exit 1
fi

PHONE_SSH="ssh $phone_ip -p 8022 -i $PHONE_KEY"

case $1 in
    run)
        eval "$PHONE_SSH ${*:2}"
        ;;
    cp-set)
        eval "$PHONE_SSH termux-clipboard-set '$2'"
        ;;
    cp-get)
        $PHONE_SSH termux-clipboard-get
        ;;
    pull)
        scp -P 8022 -i "$PHONE_KEY" "$phone_ip":"$2" "$3"
        ;;
    push)
        scp -P 8022 -i "$PHONE_KEY" "$2" "$phone_ip":"$3"
        ;;
    share)
        eval "$PHONE_SSH rm -rf ./tmp/*"
        scp -P 8022 -i "$PHONE_KEY" "$2" "$phone_ip":./tmp/
        eval "$PHONE_SSH termux-share -a send ./tmp/*"
        ;;
    mount)
        sshfs -p 8022 -o IdentityFile="$PHONE_KEY" "$phone_ip":"$2" "$3"
        ;;
    scan)
        if [ "$(id -u)" -ne 0 ]
        then
          echo Scanning IP option requires root access, please run as root. 1>&2
          exit 1
        fi
        MACtoIP
        ;;
    sms)
        $script run su -c cp /data/data/com.textra/databases/messaging.db /sdcard/tmp/sms.db
        $script pull  /sdcard/tmp/sms.db /tmp/ >/dev/null
        sqlite3 -line /tmp/sms.db 'select text from messages order by _id desc limit 1' |
        awk -F " = " '{print $2}'
        ;;
    *)
        echo "Mini Termux Controller - github/Kebablord

scan                *  scan network to update phone's current IP adress
run <param>         -  run ssh commands or connect ssh terminal if no arg passed
cp-set <string>     -  copy the string to phone clipboard
cp-get              -  return the string from phone clipboard
sms                 -  display latest sms, useful for verification codes (root)
pull  <src> <dest>  -  pull the file from phone to computer
push  <src> <dest>  -  push the file to phone from computer
share <src>         -  share the media from computer to phone apps like whatsapp, telegram
mount <src> <dest>  -  use SSHFS to mount specific phone folder to linux folder
"
    ;;
esac

